### ISSUE TITLE
SailException

### ISSUE THREAD

**Issue by robbinsr** [hammar/NeoTest#1]
Error experienced:

Exception in thread "main" java.lang.NoClassDefFoundError: SailException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: SailException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

I am sure this is caused by my novice Java skills...but just in case I thought I would put it here.

THANK  YOU for sharing this wonderful code. Neo4j seems to be very robust and there are many resources framed as RDF that I would like to get into Neo4j.

Steps I used were:

1. Open Eclipse.

Eclipse Java EE IDE for Web Developers.
Version: Luna Service Release 1a (4.4.1)
Build id: 20150109-0600

2. Install Gradle(s) plugins via Eclipse Marketplace.

Gradle IDE Pack 3.6.x+0.17
Gradle Integration for Eclipse 3.6.3 and 3.6.4

3. Clone your GitHub master from within Eclipse using Git View.

4. Copy currencies.ttl from Resources to my http://github.com/robbinsr/store/currencies.ttl and change your source code. to reflect change.

5. Run source from within Eclipse.

Thank you for any advice, as that is what seems most likely.

p.s. Note that prior to doing this what appears to be close to the right way, I built and tried several different projects (in different workspaces) where I cut and paste your code and eliminated package naming issues, then included jars as appropriate, and still ran into the SailException problem when all was finally configured.

p.p.s. I'm wondering whether you ran into this problem. Again, thank you, and very sorry about all the details, but I just wanted to provide as much information as could be helpful. Again, thank you so much for this great code.,

**Comment by robbinsr** [comment]
http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/sail/SailException.html

**Comment by hammar** [comment]
Hi,

Your issue indicates that something is wrong with your classpath, i.e., that the SAIL libraries aren't found. I'm not familiar with the Gradle plugin for Eclipse, but have rather used console Gradle. There are a couple of hoops to jump through to get the environment working. What works for me is the following sequence:

    gradle build
    gradle eclipse

Then: 

1. Import the project into Eclipse. 
2. Remove the faulty project dependency on neo4j-2.0.1.pom from the build path (only JARs should be set as dependencies, someone building these projects messed up)
3. Tell Eclipse to use JavaSE 7 (for some reason it always insists on using 1.6 for me, which does not work)
4. Run As -> Java Application

If everything works, you get the following output:

```
13:10:50.594 [main] WARN  o.neo4j.kernel.EmbeddedGraphDatabase - You are using an unsupported version of the Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
13:10:52.146 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
13:10:52.147 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
13:10:52.148 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
13:10:52.148 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.n3.N3ParserFactory
13:10:52.149 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfjson.RDFJSONParserFactory
13:10:52.149 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
13:10:52.150 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trix.TriXParserFactory
13:10:52.151 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
13:10:52.151 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trig.TriGParserFactory
13:10:52.242 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.XMLSchemaDatatypeHandler
13:10:52.242 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.RDFDatatypeHandler
13:10:52.243 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.DBPediaDatatypeHandler
13:10:52.243 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.VirtuosoGeometryDatatypeHandler
13:10:52.244 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.GeoSPARQLDatatypeHandler
13:10:52.245 [main] DEBUG o.o.rio.LanguageHandlerRegistry - Registered service class org.openrdf.rio.languages.RFC3066LanguageHandler
Imported data.
```

Your Neo4J database should at this point be located in the subdirectory "graph.db", from which you can move it over to a Neo4J server to see how it is structured.

**Comment by robbinsr** [comment]
Karl,
THANK YOU so much!
All the very best,
Russ
